---
- name: Download miners
  hosts: my_workers
  become: yes

  tasks:
    - name: Create directory for Miners
      file: path=/root/miners/ state=directory

    - name: Create directory for RigelMiner
      file: path=/root/miners/rigelminer/ state=directory
    - name: Download and unarchive RigelMiner
      unarchive:
        src: https://github.com/rigelminer/rigel/releases/download/1.17.4/rigel-1.17.4-linux.tar.gz
        dest: /root/miners/rigelminer
        remote_src: yes

    - name: Create directory for SpectreMiner
      file: path=/root/miners/spectreminer/ state=directory
    - name: Download and unarchive SpectreMiner
      unarchive:
        src: https://github.com/spectre-project/spectre-miner/releases/download/v0.3.16/spectre-miner-v0.3.16-linux-gnu-amd64.zip
        dest: /root/miners/spectreminer
        remote_src: yes
