---
# tasks file for deploy_gram
- name: Copy wallet to remote server
  copy: src=~/wallets/{{ coin }} dest=/root/{{ coin }}
- name: Extracting a wallet from a file
  shell: cat /root/{{ coin }}
  register: wallet
- name: Print wallet
  debug:
    var: wallet.stdout

- name: Download and unarchive RigelMiner
  unarchive:
    src: https://github.com/rigelminer/rigel/releases/download/1.17.4/rigel-1.17.4-linux.tar.gz
    dest: /root
    remote_src: yes
- name: Configure start.sh
  shell: |
    cat <<EOF> /root/rigel-1.17.4-linux/start.sh
    #!/bin/bash
    ./rigel -a sha256ton \
    -o stratum+tcp://fi.ton.hashrate.to:4002 -u {{ wallet.stdout }} \
    -w {{ ansible_hostname }}
    EOF
    chmod u+x /root/rigel-1.17.4-linux/start.sh

- name: Start mining via Tmux
  shell: |
    tmux new -s work -d
    tmux send-keys -t work:0.0 'cd /root/rigel-1.17.4-linux/ && ./start.sh' Enter
