---
# tasks file for deploy_spectre

- name: Copy wallet to remote server
  copy: src=~/wallets/{{ coin }} dest=/root/{{ coin }}
- name: Extracting a wallet from a file
  shell: cat /root/{{ coin }}
  register: wallet
- name: Print wallet
  debug:
    var: wallet.stdout


- name: Create directory for SpectreMiner
  file: path=/root/spectreminer/ state=directory
- name: Download and unarchive SpectreMiner
  unarchive:
    src: https://github.com/spectre-project/spectre-miner/releases/download/v0.3.16/spectre-miner-v0.3.16-linux-gnu-amd64.zip
    dest: /root/spectreminer
    remote_src: yes

- name: Start mining Spectre
  shell: |
    echo './spectre-miner-v0.3.16-linux-gnu-amd64 -a spectre:qze7lf9wnyafhnak79ltgcx9hyclpdeu9cayw48kppvkg77dh6rqsp4u0wk33 -t $(cat /proc/cpuinfo | grep processor | wc -l) --spectred-address 195.135.215.24' > /root/spectreminer/bin/start.sh
    chmod u+x /root/spectreminer/bin/start.sh
    tmux new -s spectre -d
    tmux send-keys -t spectre "cd /root/spectreminer/bin/; ./start.sh" Enter
