---
# tasks file for deploy_spectre

- name: Copy wallet to remote server
  copy: src=~/wallets/{{ coin }} dest=/root/{{ coin }}
- name: Extracting a wallet from a file
  shell: cat /root/{{ coin }}
  register: wallet
- name: Print wallet
  debug:
    var: wallet.stdout

- name: Create directory for SpectreNode
  file: path=/root/spectrenode/ state=directory
- name: Download and unarchive SpectreNode
  unarchive:
    src: https://github.com/spectre-project/rusty-spectre/releases/download/v0.3.14/rusty-spectre-v0.3.14-linux-gnu-amd64.zip 
    dest: /root/spectrenode
    remote_src: yes

- name: Create directory for SpectreMiner
  file: path=/root/spectreminer/ state=directory
- name: Download and unarchive SpectreMiner
  unarchive:
    src: https://github.com/spectre-project/spectre-miner/releases/download/v0.3.16/spectre-miner-v0.3.16-linux-gnu-amd64.zip
    dest: /root/spectreminer
    remote_src: yes

- name: Start SpectreNode via Tmux
  shell: |
    echo 'while true; do "./spectred"; sleep 2; done;' > /root/spectrenode/bin/start.sh
    chmod u+x /root/spectrenode/bin/start.sh
    tmux new -s spectrenode -d
    tmux send-keys -t spectrenode "cd /root/spectrenode/bin; ./start.sh" Enter
- name: Start mining Spectre
  shell: |
    echo 'while true; do "./spectre-miner-v0.3.16-linux-gnu-amd64" -a spectre:qze7lf9wnyafhnak79ltgcx9hyclpdeu9cayw48kppvkg77dh6rqsp4u0wk33; sleep 2; done;' > /root/spectreminer/bin/start.sh
    chmod u+x /root/spectreminer/bin/start.sh
    tmux split-window -h -t spectrenode
    tmux send-keys -t spectrenode:0.1 "cd /root/spectreminer/bin/; ./start.sh" Enter
