---
# tasks file for run_gram_zil_NE

- name: Copy wallet to remote server
  copy: src=~/wallets/{{ coin }} dest=/root/{{ coin }}
- name: Extracting a wallet from a file
  shell: cat /root/{{ coin }}
  register: wallet
- name: Print wallet
  debug:
    var: wallet.stdout

- name: Copy wallet to remote server
  copy: src=~/wallets/{{ coin2 }} dest=/root/{{ coin2 }}
- name: Extracting a wallet from a file
  shell: cat /root/{{ coin2 }}
  register: wallet2
- name: Print wallet
  debug:
    var: wallet2.stdout


- name: Stop service
  shell: |
    systemctl stop mining_nvidia
    systemctl disable mining_nvidia
    systemctl daemon-reload


- name: Create service
  shell: |
    cat <<EOF> /etc/systemd/system/mining_nvidia.service
    [Unit]
    Description=Mining NVIDIA
    After=network.target

    [Service]
    User=root
    Group=root
    Type=simple
    Restart=on-failure
    ExecStart=/root/rigelminer/rigel-1.17.4-linux/rigel -a sha256ton+zil \
        -o [1]stratum+tcp://fi.ton.hashrate.to:4002 -u [1]{{ wallet.stdout }} \
        -o [2]stratum+ssl://eu.zil.k1pool.com:1111 -u [2]{{ wallet2.stdout }} \
        -w {{ ansible_hostname }} --zil-countdown \
        --lock-cclock [1]2300 --lock-mclock [1]810 --cclock [1]300 --pl [1]320 \
        --lock-cclock [2]2500 --lock-mclock [2]X --mclock [2]1000 --cclock [2]100 --pl [2]300 --fan-control 75

    [Install]
    WantedBy=multi-user.target
    EOF

- name: Enable service
  shell: |
    systemctl daemon-reload
    systemctl start mining_nvidia
    systemctl enable mining_nvidia
    systemctl status mining_nvidia --no-pager

